name: vendor
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  shared_preferences: ^2.5.3
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash1.png

# Top-level flutter_native_splash configuration
flutter_native_splash:
  color: "#6A11CB"
  image: assets/images/splash1.png
  android: true
  ios: true
  web: false
